#############################################################################
# Makefile for building: untitled1.app/Contents/MacOS/untitled1
# Generated by qmake (3.0) (Qt 5.2.1)
# Project:  untitled1/untitled1.pro
# Template: app
# Command: /Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/bin/qmake -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile untitled1/untitled1.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W -fPIE $(DEFINES)
INCPATH       = -I../../Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang -Iuntitled1 -I../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers -I../../Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/Versions/5/Headers -I../../Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/Versions/5/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/OpenGL.framework/Versions/A/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I. -F/Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/lib
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -headerpad_max_install_names -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -stdlib=libc++ -mmacosx-version-min=10.7
LIBS          = $(SUBLIBS) -F/Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework OpenGL -framework AGL 
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
QMAKE         = /Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = untitled1/main.cpp \
		untitled1/editwindow.cpp \
		untitled1/mul8_mainview.cpp moc_mul8_mainview.cpp
OBJECTS       = main.o \
		editwindow.o \
		mul8_mainview.o \
		moc_mul8_mainview.o
DIST          = ../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/qdevice.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/device_config.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/common/unix.conf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/common/mac.conf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/common/macx.conf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang.conf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang-mac.conf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/qconfig.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_post.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/c++11.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qml_debug.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/declarative_debug.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resources.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/moc.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/opengl.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/uic.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/thread.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/yacc.prf \
		../Qt5.2.1/5.2.1/clang_64/mkspecs/features/lex.prf \
		untitled1/untitled1/untitled1.pro \
		untitled1/untitled1.pro
QMAKE_TARGET  = untitled1
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = untitled1.app/Contents/MacOS/untitled1

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-isysroot \
		/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile untitled1.app/Contents/PkgInfo untitled1.app/Contents/Resources/empty.lproj $(TARGET)

$(TARGET): ui_mul8_mainview.h $(OBJECTS)  
	@test -d untitled1.app/Contents/MacOS/ || mkdir -p untitled1.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: untitled1/untitled1.pro ../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_pre.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/qdevice.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/device_config.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/shell-unix.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/unix.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/mac.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/macx.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang-mac.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/qconfig.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_functions.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_config.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_post.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_pre.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resolve_config.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_post.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/c++11.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/sdk.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_post.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qml_debug.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/declarative_debug.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/warn_on.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resources.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/moc.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/opengl.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/uic.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/thread.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/rez.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/testcase_targets.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exceptions.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/yacc.prf \
		../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/lex.prf \
		untitled1/untitled1.pro \
		/Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		/Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile untitled1/untitled1.pro
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_pre.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/qdevice.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/device_config.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/shell-unix.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/unix.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/mac.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/macx.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/common/clang-mac.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/qconfig.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_functions.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt_config.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/macx-clang/qmake.conf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/spec_post.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exclusive_builds.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_pre.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_pre.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resolve_config.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/default_post.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/c++11.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/sdk.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/default_post.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/objective_c.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qml_debug.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/declarative_debug.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/warn_on.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/qt.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/resources.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/moc.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/opengl.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/uic.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/unix/thread.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/mac/rez.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/testcase_targets.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/exceptions.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/yacc.prf:
../../Qt5.2.1/5.2.1/clang_64/mkspecs/features/lex.prf:
untitled1/untitled1.pro:
/Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
/Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile untitled1/untitled1.pro

qmake_all: FORCE

untitled1.app/Contents/PkgInfo: 
	@test -d untitled1.app/Contents || mkdir -p untitled1.app/Contents
	@$(DEL_FILE) untitled1.app/Contents/PkgInfo
	@echo "APPL????" >untitled1.app/Contents/PkgInfo
untitled1.app/Contents/Resources/empty.lproj: 
	@test -d untitled1.app/Contents/Resources || mkdir -p untitled1.app/Contents/Resources
	@touch untitled1.app/Contents/Resources/empty.lproj
	
: 
	@$(DEL_FILE) 
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,@TYPEINFO@,????,g" -e "s,@ICON@,,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.untitled1,g" -e "s,@EXECUTABLE@,untitled1,g" -e "s,@TYPEINFO@,????,g"  >
dist: 
	@test -d .tmp/untitled11.0.0 || mkdir -p .tmp/untitled11.0.0
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/untitled11.0.0/ && $(COPY_FILE) --parents untitled1/mul8_mainview.h .tmp/untitled11.0.0/ && $(COPY_FILE) --parents untitled1/main.cpp untitled1/editwindow.cpp untitled1/mul8_mainview.cpp .tmp/untitled11.0.0/ && $(COPY_FILE) --parents untitled1/mul8_mainview.ui .tmp/untitled11.0.0/ && (cd `dirname .tmp/untitled11.0.0` && $(TAR) untitled11.0.0.tar untitled11.0.0 && $(COMPRESS) untitled11.0.0.tar) && $(MOVE) `dirname .tmp/untitled11.0.0`/untitled11.0.0.tar.gz . && $(DEL_FILE) -r .tmp/untitled11.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r untitled1.app
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_mul8_mainview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mul8_mainview.cpp
moc_mul8_mainview.cpp: ../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		untitled1/mul8_mainview.h
	/Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/bin/moc $(DEFINES) -D__APPLE__ -D__GNUC__=4 $(INCPATH) untitled1/mul8_mainview.h -o moc_mul8_mainview.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mul8_mainview.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mul8_mainview.h
ui_mul8_mainview.h: untitled1/mul8_mainview.ui
	/Users/blinginbeckwith/Qt5.2.1/5.2.1/clang_64/bin/uic untitled1/mul8_mainview.ui -o ui_mul8_mainview.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: untitled1/main.cpp untitled1/mul8_mainview.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QApplication \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o untitled1/main.cpp

editwindow.o: untitled1/editwindow.cpp untitled1/mul8_mainview.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		ui_mul8_mainview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editwindow.o untitled1/editwindow.cpp

mul8_mainview.o: untitled1/mul8_mainview.cpp untitled1/mul8_mainview.h \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/QMainWindow \
		../../Qt5.2.1/5.2.1/clang_64/lib/QtWidgets.framework/Versions/5/Headers/qmainwindow.h \
		ui_mul8_mainview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mul8_mainview.o untitled1/mul8_mainview.cpp

moc_mul8_mainview.o: moc_mul8_mainview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mul8_mainview.o moc_mul8_mainview.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

