######################################################################
# Automatically generated by qmake (2.01a) Thu Apr 24 23:29:31 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mul8_mainview.h
FORMS += mul8_mainview.ui
SOURCES += editwindow.cpp main.cpp mul8_mainview.cpp
